import type { Template } from '@pdfme/common';
import { text, line, rectangle } from '@pdfme/schemas';

export const template: Template = {
  "schemas": [
    [
      {
        "name": "V_Type",
        "type": "text",
        "content": "",
        "position": {
          "x": 51.27,
          "y": 75
        },
        "width": 37.57,
        "height": 7.14,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": true,
        "required": false,
        "readOnly": false
      },
      {
        "name": "name",
        "type": "text",
        "content": "",
        "position": {
          "x": 36.13,
          "y": 90
        },
        "width": 160.07,
        "height": 7.14,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false
      },
      {
        "name": "date",
        "type": "text",
        "content": "",
        "position": {
          "x": 36.07,
          "y": 98
        },
        "width": 37.57,
        "height": 7.14,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false
      },
      {
        "name": "myntCard",
        "type": "text",
        "content": "",
        "position": {
          "x": 27,
          "y": 125
        },
        "width": 55,
        "height": 6,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "overflow": "visible"
      },
      {
        "name": "bankName",
        "type": "text",
        "content": "",
        "position": {
          "x": 105.01,
          "y": 120
        },
        "width": 92.87,
        "height": 7.14,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false
      },
      {
        "name": "clearing",
        "type": "text",
        "content": "",
        "position": {
          "x": 92,
          "y": 135
        },
        "width": 18.26,
        "height": 7.14,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false
      },
      {
        "name": "bankNum",
        "type": "text",
        "content": "",
        "position": {
          "x": 115,
          "y": 135
        },
        "width": 72.5,
        "height": 7.14,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false
      },
      {
        "name": "purchaseDate",
        "type": "text",
        "content": "",
        "position": {
          "x": 42,
          "y": 150
        },
        "width": 28,
        "height": 7.14,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false
      },
      {
        "name": "ammount",
        "type": "text",
        "content": "",
        "position": {
          "x": 42,
          "y": 160
        },
        "width": 20,
        "height": 7.14,
        "rotate": 0,
        "alignment": "right",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false
      },
      {
        "name": "numReceipts",
        "type": "text",
        "content": "",
        "position": {
          "x": 105.18,
          "y": 149.55
        },
        "width": 22.49,
        "height": 7.14,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "fontName": "Roboto",
        "overflow": "visible"
      },
      {
        "name": "budgetManager",
        "type": "text",
        "content": "",
        "position": {
          "x": 160,
          "y": 152
        },
        "width": 38,
        "height": 7.14,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false,
        "overflow": "visible"
      },
      {
        "name": "descrition",
        "type": "text",
        "content": "",
        "position": {
          "x": 14.68,
          "y": 175.05
        },
        "width": 113.51,
        "height": 97.37,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": false
      },
      {
        "name": "field4",
        "type": "text",
        "content": "8 8888     ,88'  ,o888888o.     b.             8     ,o888888o.    8 8888          8 8888     ,o888888o.          .8.                    8 8888888888   8 8888  `8.`8888.      ,8'  ,o888888o.      d888888o.   8 8888888888   8 8888     ,88' 8888888 8888888888  8 8888     ,o888888o.     b.             8 8 8888888888   b.             8 \n8 8888    ,88'. 8888     `88.   888o.          8    8888     `88.  8 8888          8 8888    8888     `88.       .888.                   8 8888         8 8888   `8.`8888.    ,8'  8888     `88.  .`8888:' `88. 8 8888         8 8888    ,88'        8 8888        8 8888  . 8888     `88.   888o.          8 8 8888         888o.          8 \n8 8888   ,88',8 8888       `8b  Y88888o.       8 ,8 8888       `8. 8 8888          8 8888 ,8 8888       `8.     :88888.                  8 8888         8 8888    `8.`8888.  ,8',8 8888       `8. 8.`8888.   Y8 8 8888         8 8888   ,88'         8 8888        8 8888 ,8 8888       `8b  Y88888o.       8 8 8888         Y88888o.       8 \n8 8888  ,88' 88 8888        `8b .`Y888888o.    8 88 8888           8 8888          8 8888 88 8888              . `88888.                 8 8888         8 8888     `8.`8888.,8' 88 8888           `8.`8888.     8 8888         8 8888  ,88'          8 8888        8 8888 88 8888        `8b .`Y888888o.    8 8 8888         .`Y888888o.    8 \n8 8888 ,88'  88 8888         88 8o. `Y888888o. 8 88 8888           8 8888          8 8888 88 8888             .8. `88888.                8 888888888888 8 8888      `8.`88888'  88 8888            `8.`8888.    8 888888888888 8 8888 ,88'           8 8888        8 8888 88 8888         88 8o. `Y888888o. 8 8 888888888888 8o. `Y888888o. 8 \n8 8888 88'   88 8888         88 8`Y8o. `Y88888o8 88 8888           8 8888          8 8888 88 8888            .8`8. `88888.               8 8888         8 8888       `8. 8888   88 8888             `8.`8888.   8 8888         8 8888 88'            8 8888        8 8888 88 8888         88 8`Y8o. `Y88888o8 8 8888         8`Y8o. `Y88888o8 \n8 888888<    88 8888        ,8P 8   `Y8o. `Y8888 88 8888   8888888 8 8888          8 8888 88 8888   8888888 .8' `8. `88888.              8 8888         8 8888        `8 8888   88 8888   8888888    `8.`8888.  8 8888         8 888888<             8 8888        8 8888 88 8888        ,8P 8   `Y8o. `Y8888 8 8888         8   `Y8o. `Y8888 \n8 8888 `Y8.  `8 8888       ,8P  8      `Y8o. `Y8 `8 8888       .8' 8 8888          8 8888 `8 8888       .8'.8'   `8. `88888.             8 8888         8 8888         8 8888   `8 8888       .8'8b   `8.`8888. 8 8888         8 8888 `Y8.           8 8888        8 8888 `8 8888       ,8P  8      `Y8o. `Y8 8 8888         8      `Y8o. `Y8 \n8 8888   `Y8. ` 8888     ,88'   8         `Y8o.`    8888     ,88'  8 8888          8 8888    8888     ,88'.888888888. `88888.            8 8888         8 8888         8 8888      8888     ,88' `8b.  ;8.`8888 8 8888         8 8888   `Y8.         8 8888        8 8888  ` 8888     ,88'   8         `Y8o.` 8 8888         8         `Y8o.` \n8 8888     `Y8.  `8888888P'     8            `Yo     `8888888P'    8 888888888888  8 8888     `8888888P' .8'       `8. `88888.           8 8888         8 888888888888 8 8888       `8888888P'    `Y8888P ,88P' 8 888888888888 8 8888     `Y8.       8 8888        8 8888     `8888888P'     8            `Yo 8 888888888888 8            `Yo",
        "position": {
          "x": 11.32,
          "y": 21.58
        },
        "width": 187.59,
        "height": 43.39,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "middle",
        "fontSize": 3.5,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "fontName": "Arial",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true,
        "overflow": "visible"
      },
      {
        "name": "field6",
        "type": "text",
        "content": "Verifikatstyp:",
        "position": {
          "x": 20.06,
          "y": 75
        },
        "width": 35.19,
        "height": 7.41,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7",
        "type": "text",
        "content": "Namn:",
        "position": {
          "x": 19,
          "y": 90
        },
        "width": 16,
        "height": 5.82,
        "rotate": 0,
        "alignment": "right",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7 copy",
        "type": "text",
        "content": "Ifyllt:",
        "position": {
          "x": 19,
          "y": 98
        },
        "width": 16,
        "height": 5.82,
        "rotate": 0,
        "alignment": "right",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7 copy 2",
        "type": "text",
        "content": "Mynt",
        "position": {
          "x": 48.05,
          "y": 111.04
        },
        "width": 13.23,
        "height": 5.82,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": true,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7 copy 3",
        "type": "text",
        "content": "Privat utlägg",
        "position": {
          "x": 89.28,
          "y": 110.19
        },
        "width": 108.21,
        "height": 5.82,
        "rotate": 0,
        "alignment": "center",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": true,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7 copy 4",
        "type": "text",
        "content": "Kort:",
        "position": {
          "x": 15,
          "y": 125
        },
        "width": 13,
        "height": 6,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true,
        "overflow": "visible"
      },
      {
        "name": "field7 copy 5",
        "type": "text",
        "content": "Bank:",
        "position": {
          "x": 92.12,
          "y": 120
        },
        "width": 13.23,
        "height": 5.82,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7 copy 6",
        "type": "text",
        "content": "Clearing",
        "position": {
          "x": 92,
          "y": 128
        },
        "width": 19.31,
        "height": 5.82,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7 copy 7",
        "type": "text",
        "content": "Kontonummer",
        "position": {
          "x": 115,
          "y": 128
        },
        "width": 52.92,
        "height": 5.82,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7 copy 8",
        "type": "text",
        "content": "Affärsdatum:",
        "position": {
          "x": 11,
          "y": 150
        },
        "width": 30,
        "height": 5.82,
        "rotate": 0,
        "alignment": "right",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7 copy 9",
        "type": "text",
        "content": "Antal kvitton:",
        "position": {
          "x": 73,
          "y": 150
        },
        "width": 30,
        "height": 5.82,
        "rotate": 0,
        "alignment": "right",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7 copy 12",
        "type": "text",
        "content": "Belopp:",
        "position": {
          "x": 11,
          "y": 160
        },
        "width": 30,
        "height": 5.82,
        "rotate": 0,
        "alignment": "right",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7 copy 15",
        "type": "text",
        "content": "kr",
        "position": {
          "x": 63,
          "y": 160
        },
        "width": 30,
        "height": 5.82,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field7 copy 10",
        "type": "text",
        "content": "Ansvarspost:",
        "position": {
          "x": 130,
          "y": 153
        },
        "width": 30,
        "height": 5.82,
        "rotate": 0,
        "alignment": "right",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true,
        "overflow": "visible"
      },
      {
        "name": "field7 copy 13",
        "type": "text",
        "content": "Beskrivning:",
        "position": {
          "x": 14.66,
          "y": 168.13
        },
        "width": 30,
        "height": 5.82,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 13,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field39",
        "type": "text",
        "content": "CASH: cash@t.kth.se\nKBM: kbm@t.kth.se\nEKO: eko-mottagningen@t.kth.se\nJUBELCASH: jubelcash@t.kth.se",
        "position": {
          "x": 134.08,
          "y": 174.52
        },
        "width": 63.5,
        "height": 26.99,
        "rotate": 0,
        "alignment": "right",
        "verticalAlignment": "top",
        "fontSize": 11,
        "lineHeight": 1.3,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true,
        "fontName": "Roboto",
        "overflow": "visible"
      },
      {
        "name": "field39 copy",
        "type": "text",
        "content": "Kontaktuppgifter:",
        "position": {
          "x": 133.76,
          "y": 169.45
        },
        "width": 63.5,
        "height": 5.29,
        "rotate": 0,
        "alignment": "right",
        "verticalAlignment": "top",
        "fontSize": 12,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": true,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field39 copy 2",
        "type": "text",
        "content": "THS, Flygsektionen\nDrottning Kristinas väg 29\n114 29, Stockholm\n802430-2559",
        "position": {
          "x": 133,
          "y": 256.62
        },
        "width": 64,
        "height": 17.99,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "top",
        "fontSize": 11,
        "lineHeight": 1,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true
      },
      {
        "name": "field39 copy 3",
        "type": "text",
        "content": "Detta verifikat bör skickas till respektive ansvarig enligt mailaddresserna ovanför.\n\nVid frågor om ett kvittos giltighet, kontakta respektive ekonomiansvarig.",
        "position": {
          "x": 132.97,
          "y": 203.76
        },
        "width": 64.03,
        "height": 49.74,
        "rotate": 0,
        "alignment": "left",
        "verticalAlignment": "middle",
        "fontSize": 10,
        "lineHeight": 1.2,
        "characterSpacing": 0,
        "fontColor": "#000000",
        "backgroundColor": "",
        "opacity": 1,
        "strikethrough": false,
        "underline": false,
        "required": false,
        "readOnly": true,
        "fontName": "Roboto",
        "overflow": "visible"
      },
      {
        "name": "field15 copy",
        "type": "line",
        "position": {
          "x": 10,
          "y": 85.65
        },
        "width": 190,
        "height": 0.75,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field15 copy 2",
        "type": "line",
        "position": {
          "x": 10,
          "y": 107
        },
        "width": 190,
        "height": 0.75,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field15 copy 3",
        "type": "line",
        "position": {
          "x": 10,
          "y": 144
        },
        "width": 190,
        "height": 0.75,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field_dash 1",
        "type": "line",
        "position": {
          "x": 87.5,
          "y": 107.2
        },
        "width": 0.25,
        "height": 3,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field_dash 2",
        "type": "line",
        "position": {
          "x": 87.5,
          "y": 112
        },
        "width": 0.25,
        "height": 3,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field_dash 3",
        "type": "line",
        "position": {
          "x": 87.5,
          "y": 117
        },
        "width": 0.25,
        "height": 3,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field_dash 4",
        "type": "line",
        "position": {
          "x": 87.5,
          "y": 122
        },
        "width": 0.25,
        "height": 3,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field_dash 5",
        "type": "line",
        "position": {
          "x": 87.5,
          "y": 127
        },
        "width": 0.25,
        "height": 3,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field_dash 6",
        "type": "line",
        "position": {
          "x": 87.5,
          "y": 132
        },
        "width": 0.25,
        "height": 3,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field_dash 7",
        "type": "line",
        "position": {
          "x": 87.5,
          "y": 137
        },
        "width": 0.25,
        "height": 3,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field_dash 8",
        "type": "line",
        "position": {
          "x": 87.5,
          "y": 142
        },
        "width": 0.25,
        "height": 2.5,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field37",
        "type": "line",
        "position": {
          "x": 130,
          "y": 167
        },
        "width": 70,
        "height": 0.5,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field37 copy 2",
        "type": "line",
        "position": {
          "x": 130,
          "y": 254
        },
        "width": 70,
        "height": 0.5,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field37 copy",
        "type": "line",
        "position": {
          "x": 130,
          "y": 203
        },
        "width": 70,
        "height": 0.5,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      },
      {
        "name": "field45",
        "type": "rectangle",
        "position": {
          "x": 10,
          "y": 69.3
        },
        "width": 189.97,
        "height": 207.7,
        "rotate": 0,
        "opacity": 1,
        "borderWidth": 1,
        "borderColor": "#000000",
        "color": "",
        "readOnly": true,
        "radius": 0,
        "required": false,
        "content": ""
      },
      {
        "name": "field2",
        "type": "rectangle",
        "position": {
          "x": 10,
          "y": 20
        },
        "width": 189.97,
        "height": 47.36,
        "rotate": 0,
        "opacity": 1,
        "borderWidth": 1,
        "borderColor": "#000000",
        "color": "",
        "readOnly": true,
        "radius": 0,
        "required": false,
        "content": ""
      },
      {
        "name": "field52",
        "type": "line",
        "position": {
          "x": 130,
          "y": 144
        },
        "width": 1,
        "height": 132.5,
        "rotate": 0,
        "opacity": 1,
        "readOnly": true,
        "color": "#000000",
        "required": false,
        "content": ""
      }
    ]
  ],
  "basePdf": {
    "width": 210,
    "height": 297,
    "padding": [
      20,
      10,
      20,
      10
    ]
  },
  "pdfmeVersion": "6.1.11"
}